module.exports = {
  TIMESTAMP_WINDOW: 3600, // 秒
  RETARGET_PERIOD: 5, // ブロック
  BLOCK_TIME: 150, // 秒
  MAX_RETARGET: 4, // 難易度の倍数
  INITIAL_MINING_REWARD: 50e8, // 50e8 == 50 億 サトシ (50 BTC)
  REWARD_HALVING_PERIOD: 100, // ブロック
  REWARD_MATURING_PERIOD: 3, // ブロック
  STANDARD_RELAY_FEERATE: 1, // サトシ / バイト
  STANDARD_DUST_OUTPUT: 546, // サトシ
  P2P_PROTOCOL_VERSION: 1,
  USER_AGENT: '/FLOC:0.0.1/',
  P2P_PORT: 8333,
  GENESIS_BITS: 0x1d7fff00,
}
